export const translations = {
  en: {
    // Navbar
    nav: {
      appName: 'Uzhavar Vazhi',
    },
    // Hero
    hero: {
      title: 'Know your rights. Get your loan.',
      subtitle: 'Covering all 38 districts · 12+ schemes · Free forever',
    },
    // Steps
    steps: {
      step1: 'Your farm details',
      step2: 'Eligibility results',
      step3: 'Your profile',
      step1Short: 'Step {{current}} of 3',
    },
    // Form
    form: {
      district: 'District',
      districtPlaceholder: 'Select your district',
      crop: 'Crop grown',
      cropPlaceholder: 'Select your crop',
      landSize: 'Land size (in acres)',
      landSizeHelper: 'Minimum 0.5 acres to qualify for most schemes',
      ownership: 'Land ownership',
      ownershipOwned: 'Owned',
      ownershipTenant: 'Tenant',
      ownershipLeasehold: 'Leasehold',
      checkEligibility: 'Check my eligibility',
      changeDetails: 'Change details',
    },
    // Results
    results: {
      eligibilityScore: 'ELIGIBILITY SCORE',
      high: 'HIGH ELIGIBILITY',
      medium: 'MEDIUM ELIGIBILITY',
      loanSchemes: 'Loan schemes',
      insurance: 'Insurance',
      mspToday: "Today's MSP",
      seasonRisk: 'Season risk',
      maxLoan: 'Maximum loan amount',
      guaranteedPrice: 'Government guaranteed minimum price',
      season: '2025–26 season',
      risk: {
        low: 'Low risk',
        medium: 'Medium risk',
        high: 'High risk',
        monsoonImpact: 'Northeast monsoon impact',
      },
    },
    // Schemes
    schemes: {
      kcc: 'KCC',
      kccFull: 'Kisan Credit Card',
      cooperative: 'Cooperative loan',
      nabard: 'NABARD scheme',
      pmfby: 'PMFBY',
      pmfbyFull: 'Pradhan Mantri Fasal Bima Yojana',
      tnDelta: 'TN Delta Relief',
      eligible: 'Eligible',
      verify: 'Verify at branch',
    },
    // PDF
    pdf: {
      title: 'Farmer Financial Profile Report',
      download: 'Download PDF',
      share: 'Share on WhatsApp',
      backToResults: 'Back to results',
      newFarmer: 'New farmer',
      generated: 'Generated by',
    },
    // Profile
    profile: {
      farmerName: 'Farmer name',
      district: 'District',
      crop: 'Crop',
      season: 'Season',
      landSize: 'Land size',
      ownership: 'Ownership',
      nearestBranch: 'Nearest PACS branch',
    },
    // Footer
    footer: {
      made: 'Made for Tamil Nadu farmers',
      year: '2026',
    },
  },
  ta: {
    // Navbar
    nav: {
      appName: 'உழவர் வழி',
    },
    // Hero
    hero: {
      title: 'உங்கள் உரிமைகளை அறியுங்கள். உங்கள் கடனை பெறுங்கள்.',
      subtitle: '38 மாவட்டங்கள் · 12+ திட்டங்கள் · எப்போதும் இலவசம்',
    },
    // Steps
    steps: {
      step1: 'உங்கள் பண்ணை',
      step2: 'தகுதி முடிவுகள்',
      step3: 'சுயவிவரம்',
      step1Short: 'படி� {{current}} / 3',
    },
    // Form
    form: {
      district: 'மாவட்டம்',
      districtPlaceholder: 'உங்கள் மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
      crop: 'வளர்க்கும் பயிர்',
      cropPlaceholder: 'உங்கள் பயிரைத் தேர்ந்தெடுக்கவும்',
      landSize: 'நில அளவு (ஏக்கரில்)',
      landSizeHelper: 'பெரும்பாலான திட்டங்களுக்கு குறைந்தது 0.5 ஏக்கர் தேவை',
      ownership: 'நில உரிமை வகை',
      ownershipOwned: 'சொந்தம்',
      ownershipTenant: 'குத்தகை',
      ownershipLeasehold: 'குத்தகை ஒப்பந்தம்',
      checkEligibility: 'தகுதியை சரிபார்க்க',
      changeDetails: 'விவரங்களை மாற்றவும்',
    },
    // Results
    results: {
      eligibilityScore: 'தகுதி மதிப்பீடு',
      high: 'உயர் தகுதி',
      medium: 'நடுத்தர தகுதி',
      loanSchemes: 'கடன் திட்டங்கள்',
      insurance: 'காப்பீட்டு திட்டங்கள்',
      mspToday: 'இன்றைய MSP',
      seasonRisk: 'பருவகால அபாயம்',
      maxLoan: 'அதிகபட்ச கடன் தொகை',
      guaranteedPrice: 'அரசு உத்தரவாதம்',
      season: '2025–26 பருவம்',
      risk: {
        low: 'குறைந்த ஆபத்து',
        medium: 'நடுத்தர ஆபத்து',
        high: 'அதிக ஆபத்து',
        monsoonImpact: 'வடகிழக்கு பருவமழை தாக்கம்',
      },
    },
    // Schemes
    schemes: {
      kcc: 'கிசான் கடன் அட்டை',
      kccFull: 'கிசான் கடன் அட்டை',
      cooperative: 'கூட்டுறவு கடன்',
      nabard: 'நபார்டு திட்டம்',
      pmfby: 'PMFBY',
      pmfbyFull: 'பிரதம மந்திரி பசல் பீமா யோஜனா',
      tnDelta: 'டெல்டா நிவாரணம்',
      eligible: 'தகுதி உடைய',
      verify: 'கிளையில் சரிபார்க்கவும்',
    },
    // PDF
    pdf: {
      title: 'விவசாயி நிதி சுயவிவர அறிக்கை',
      download: 'PDF பதிவிறக்கம்',
      share: 'வாட்ஸ்அப்பில் பகிர்',
      backToResults: 'முடிவுகளுக்குத் திரும்பு',
      newFarmer: 'புதிய விவசாயி',
      generated: 'உருவாக்கப்பட்டது',
    },
    // Profile
    profile: {
      farmerName: 'விவசாயி பெயர்',
      district: 'மாவட்டம்',
      crop: 'பயிர்',
      season: 'பருவம்',
      landSize: 'நில அளவு',
      ownership: 'உரிமை வகை',
      nearestBranch: 'அருகிலுள்ள PACS கிளை',
    },
    // Footer
    footer: {
      made: 'தமிழ்நாட்டு விவசாயிகளுக்காக உருவாக்கப்பட்டது',
      year: '2026',
    },
  },
};

export type Language = 'en' | 'ta';
export type Translations = typeof translations.en;
